### ISSUE TITLE
Run ./gradlew build fail

### ISSUE THREAD

**Issue by v-jiaodi** [Azure-Samples/pubsub-dapr-aks-java#1]
**Describe the issue:**
- issue1
When executing `make deploy-local` according to [README.md](https://github.com/Azure-Samples/pubsub-dapr-aks-java/blob/main/README.md), the error is as follows:
![image](https://github.com/Azure-Samples/pubsub-dapr-aks-java/assets/80496810/45327e50-dbdd-442f-9ce4-3f096241a4ab)

- issue2
When running  `azd up`, get seem error as follows:
![image](https://github.com/Azure-Samples/pubsub-dapr-aks-java/assets/80496810/389dcf84-cccf-4f18-829c-684e9c294c35)

**Repro Steps:**
- issue1:
1. Clone the code to local.
2. Run `make start-local`
3. Run `make deploy-local`

- issue2:
1. Run `azd auth login`
2. Run `azd up`

**Environment:**
- OS: Windows desktop.

**Expected behavior:**
  Run `make deploy-local` and `azd up` can pass.

@hemarina for notification.

**Comment by ross-p-smith** [comment]
Hi @v-jiaodi - were you running this in a DevContainer? You say it is in Windows Desktop - is that using WSL?

I've just cloned the repo and run those steps and it works for me in a DevContainer in WSL.

**Comment by macromania** [comment]
@v-jiaodi  and @hemarina

These issues are fixed now. Please have another round of testing 😇

**Comment by v-jiaodi** [comment]
@macromania Testing again, this issue still exists.
