### ISSUE TITLE
dapr-cli doesnt install in devcontainer

### ISSUE THREAD

**Issue by ross-p-smith** [Azure-Samples/pubsub-dapr-aks-java#2]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Open the solution in a DevContainer

### Any log messages given by the failure
>

### Expected/desired behavior
> The Devcontainer opens

**Comment by macromania** [comment]
Fixed with #3
